sudo: false # disable sudo to speed up the build

language: python

python:
  - "2.7"
  - "3.4"
  # - "3.6"

services:
  - xvfb

before_install:
  - pip install coverage==4.5.4  # temporary fix for coveralls
  - pip install coveralls
  - pip install python-coveralls
  - pip install codecov
  - pip install scipy
  - pip install PySide

# command to install dependencies
install:
  - pip install .
  - pip install -r test_requirements.txt

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - coverage run --source slitronomy setup.py test

after_success:
  - coveralls
  - codecov
