language: python

python:
  - "2.7"
  - "3.6"

services:
  - xvfb

before_install:
  - sudo apt-get update
  - sudo updatedb
  - if [ $TRAVIS_PYTHON_VERSION == "2.7" ]; then
      pip install PySide;
    fi
  - if [ $TRAVIS_PYTHON_VERSION == "3.6" ]; then
      pip install PyQt5==5.14.0;
    fi
  - pip install coverage==4.5.4  # temporary fix for coveralls
  - pip install coveralls
  - pip install python-coveralls
  - pip install codecov

# command to install dependencies
install:
  - pip install -r test_requirements.txt
  - pip install .
  
before_script: # configure a headless display to test plot generation
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - coverage run --source slitronomy setup.py test

after_success:
  - coveralls
  - codecov
