os:
  - linux
  - osx

language: python

python:
  - 2.7
  - 3.6

jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      # osx_image: xcode11.3
  allow_failures:
    - os: osx
    # - python: 3.6

services:
  - xvfb

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get update;
      sudo updatedb;
      sudo apt install -y libnfft3-dev;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install cmake libomp;
      brew update;
      brew install fftw;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then
      export CPLUS_INCLUDE_PATH=/opt/python/2.7.15/include/python2.7;
    fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
      export CPLUS_INCLUDE_PATH=/opt/python/3.6.3/include/python3.6m;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda update --all -y
  - conda info -a
  # now we create and activate the python virtualenv
  - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
  - source activate testenv
  
install:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then
      pip install PySide;
    fi
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then
      pip install -I PyQt5==5.14.0;
    fi
  - pip install coverage==4.5.4  # temporary fix for coveralls
  - pip install coveralls
  - pip install python-coveralls
  - pip install codecov
  # risky task of installing PySAP is done here
  - ./test_pysap_install.sh
  - pip install -r test_requirements.txt
  - pip install .

before_script: # configure a headless display to test plot generation
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start

# command to run tests
script:
  - coverage run --source slitronomy setup.py test

after_success:
  - coveralls
  - codecov
